version: '2'

services:
  db:
    container_name: adaptdb
    image: mongo:3.6
    volumes:
      - adaptdb:/data/db
  adapt:
    container_name: adapt-authoring
    image: adapt-authoring
    build: .
    volumes:
      - adaptdata:/adapt_authoring
    links:
      - db
    depends_on:
      - db
    ports:
      - "${AAT_HOST_PORT}:5000"
    env_file: .env

volumes:
  adaptdata:
  adaptdb:
